# Generated by Django 5.1.6 on 2025-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_survey', '0002_student_date_joined_student_groups_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
