# Generated by Django 5.2.1 on 2025-06-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_survey', '0006_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_type', 'order']},
        ),
    ]
