# Generated by Django 5.2.1 on 2025-06-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_survey', '0007_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student_survey.survey'),
        ),
    ]
